# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacionprocedimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_aplicacion_procedimiento', models.IntegerField(blank=True, null=True)),
                ('mes_aplicacion_procedimienot', models.IntegerField(blank=True, null=True)),
                ('anio_aplicacion_procedimiento', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'aplicacionprocedimiento',
            },
        ),
        migrations.CreateModel(
            name='Asignacionexamen',
            fields=[
                ('id_asignacion_examen', models.AutoField(primary_key=True, serialize=False)),
                ('resultado_obtenido', models.TextField(blank=True, null=True)),
                ('dia_asignacion_examen', models.IntegerField(blank=True, null=True)),
                ('mes_asignacion_examen', models.IntegerField(blank=True, null=True)),
                ('anio_asignacion_examen', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'asignacionexamen',
            },
        ),
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('costo', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'cirugia',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.IntegerField(blank=True, null=True)),
                ('id_medico', models.IntegerField(blank=True, null=True)),
                ('dia', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('hora', models.IntegerField(blank=True, null=True)),
                ('minuto', models.IntegerField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'cita',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'consulta',
            },
        ),
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id_emergencia', models.AutoField(primary_key=True, serialize=False)),
                ('id_medico', models.IntegerField(blank=True, null=True)),
                ('sintomatologia_emergencia', models.TextField(blank=True, null=True)),
                ('dia_emergencia', models.IntegerField(blank=True, null=True)),
                ('mes_emergencia', models.IntegerField(blank=True, null=True)),
                ('anio_emergencia', models.IntegerField(blank=True, null=True)),
                ('hora_emergencia', models.IntegerField(blank=True, null=True)),
                ('minuto_emergencia', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'emergencia',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=20)),
                ('nombre2', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido1', models.CharField(max_length=20)),
                ('apellido2', models.CharField(blank=True, max_length=20, null=True)),
                ('pais', models.CharField(max_length=15)),
                ('division', models.CharField(max_length=15)),
                ('subdivision', models.CharField(blank=True, max_length=15, null=True)),
                ('tel_fijo', models.CharField(max_length=15)),
                ('tel_movil', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('dui', models.CharField(max_length=15, unique=True)),
                ('apellido_casada', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_empleado', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id_enfermedad', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_enfermedad', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_enfermedad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'enfermedad',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_especialidad', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_especialidad', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'especialidad',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_examen', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_examen', models.CharField(blank=True, max_length=50, null=True)),
                ('costo_examen', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'examen',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id_expediente', models.AutoField(primary_key=True, serialize=False)),
                ('id_paciente', models.IntegerField()),
                ('dia_apertura_expediente', models.IntegerField(blank=True, null=True)),
                ('mes_apertura_expediente', models.IntegerField(blank=True, null=True)),
                ('anio_apertura_expediente', models.IntegerField(blank=True, null=True)),
                ('dia_expiracion_expediente', models.IntegerField(blank=True, null=True)),
                ('mes_expiracion_expediente', models.IntegerField(blank=True, null=True)),
                ('anio_expiracion_expediente', models.IntegerField(blank=True, null=True)),
                ('numero_expediente', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'expediente',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('id_paciente', models.IntegerField(blank=True, null=True)),
                ('id_medico', models.IntegerField(blank=True, null=True)),
                ('dia_inicio_ingreso', models.IntegerField(blank=True, null=True)),
                ('mes_inicio_ingreso', models.IntegerField(blank=True, null=True)),
                ('anio_inicio_ingreso', models.IntegerField(blank=True, null=True)),
                ('dia_fin_ingreso', models.IntegerField(blank=True, null=True)),
                ('mes_fin_ingreso', models.IntegerField(blank=True, null=True)),
                ('anio_fin_ingreso', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ingreso',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_medicamento', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_medicamento', models.CharField(blank=True, max_length=50, null=True)),
                ('costo_medicamento', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'medicamento',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'medico',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('icono', models.CharField(blank=True, max_length=40, null=True)),
                ('titulo', models.CharField(blank=True, max_length=25, null=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('recurso', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('estado_civil_paciente', models.IntegerField(blank=True, null=True)),
                ('apellido_casado_paciente', models.CharField(blank=True, max_length=20, null=True)),
                ('dia_nacimiento_paciente', models.IntegerField(blank=True, null=True)),
                ('mes_nacimiento_paciente', models.IntegerField(blank=True, null=True)),
                ('anio_nacimiento_paciente', models.IntegerField(blank=True, null=True)),
                ('nombre1', models.CharField(max_length=20)),
                ('nombre2', models.CharField(max_length=20)),
                ('apellido1', models.CharField(max_length=20)),
                ('apellido2', models.CharField(blank=True, max_length=20, null=True)),
                ('pais', models.CharField(blank=True, max_length=15, null=True)),
                ('division', models.CharField(blank=True, max_length=15, null=True)),
                ('subdivision', models.CharField(blank=True, max_length=15, null=True)),
                ('tel_fijo', models.CharField(blank=True, max_length=15, null=True)),
                ('tel_movil', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('dui', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('genero', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id_padre', models.AutoField(primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=20)),
                ('nombre2', models.CharField(max_length=20)),
                ('apellido1', models.CharField(max_length=20)),
                ('apellido2', models.CharField(blank=True, max_length=20, null=True)),
                ('pais', models.CharField(max_length=15)),
                ('division', models.CharField(max_length=15)),
                ('subdivision', models.CharField(blank=True, max_length=15, null=True)),
                ('dui', models.CharField(max_length=15, unique=True)),
                ('genero', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'padre',
            },
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id_procedimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_procedimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_procedimiento', models.CharField(blank=True, max_length=15, null=True)),
                ('costo_procedimiento', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'procedimiento',
            },
        ),
        migrations.CreateModel(
            name='Realizacioncirugia',
            fields=[
                ('id_realizacion_cirugia', models.AutoField(primary_key=True, serialize=False)),
                ('id_medico', models.IntegerField(blank=True, null=True)),
                ('dia_realizacion_cirugia', models.IntegerField(blank=True, null=True)),
                ('mes_realizacion_cirugia', models.IntegerField(blank=True, null=True)),
                ('anio_realizacion_cirugia', models.IntegerField(blank=True, null=True)),
                ('hora_inicio_realizacion_cirugia', models.IntegerField(blank=True, null=True)),
                ('min_inicio_realizacion_cirugia', models.IntegerField(blank=True, null=True)),
                ('hora_fin_realizacion_cirugia', models.IntegerField(blank=True, null=True)),
                ('minuto_fin_realizacion_cirugia', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'realizacioncirugia',
            },
        ),
        migrations.CreateModel(
            name='Realizacionconsulta',
            fields=[
                ('id_realizacion_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('observacones', models.CharField(blank=True, max_length=1000, null=True)),
                ('sintom_realizacion_consulta', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'realizacionconsulta',
            },
        ),
        migrations.CreateModel(
            name='Recetamedica',
            fields=[
                ('id_receta_medica', models.AutoField(primary_key=True, serialize=False)),
                ('dosis', models.CharField(blank=True, max_length=15, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'recetamedica',
            },
        ),
        migrations.CreateModel(
            name='Recursomultimedia',
            fields=[
                ('id_recurso_multimedia', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.BinaryField(blank=True, null=True)),
                ('contentype', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'recursomultimedia',
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('nombre1', models.CharField(max_length=20)),
                ('nombre2', models.CharField(max_length=20)),
                ('apellido1', models.CharField(max_length=20)),
                ('apellido2', models.CharField(blank=True, max_length=20, null=True)),
                ('pais', models.CharField(max_length=15)),
                ('division', models.CharField(max_length=15)),
                ('subdivision', models.CharField(blank=True, max_length=15, null=True)),
                ('tel_fijo', models.CharField(blank=True, max_length=15, null=True)),
                ('tel_cel', models.CharField(blank=True, max_length=15, null=True)),
                ('id_responsable', models.AutoField(primary_key=True, serialize=False)),
                ('dui', models.CharField(max_length=15)),
            ],
            options={
                'managed': False,
                'db_table': 'responsable',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Signosvitales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('estatura', models.FloatField()),
                ('presion_arterial', models.FloatField(blank=True, null=True)),
                ('ritmo_cardiaco', models.FloatField(blank=True, null=True)),
                ('dia', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'signosvitales',
            },
        ),
        migrations.CreateModel(
            name='Tipoexamen',
            fields=[
                ('id_tipo_examen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_examen', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_tipo_examen', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tipoexamen',
            },
        ),
        migrations.CreateModel(
            name='Tipomedicamento',
            fields=[
                ('id_tipo_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('presentacion', models.CharField(max_length=25)),
            ],
            options={
                'managed': False,
                'db_table': 'tipomedicamento',
            },
        ),
        migrations.CreateModel(
            name='Tipoubicacion',
            fields=[
                ('id_tipo_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_ubicacion', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tipoubicacion',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id_tratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('recomendaciones', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tratamiento',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_ubicacion', models.CharField(blank=True, max_length=15, null=True)),
                ('nivel', models.IntegerField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('nombre_ubicacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ubicacion',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
                ('last_login', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='EnfermedadJoinConsulta',
            fields=[
                ('id_enfermedad', models.ForeignKey(db_column='id_enfermedad', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ExpedienteCO.Enfermedad')),
            ],
            options={
                'db_table': 'enfermedad_join_consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PacientePadeceEnfermedad',
            fields=[
                ('id_enfermedad', models.ForeignKey(db_column='id_enfermedad', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ExpedienteCO.Enfermedad')),
            ],
            options={
                'db_table': 'paciente_padece_enfermedad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PadrePadeceEnfermedad',
            fields=[
                ('id_enfermedad', models.ForeignKey(db_column='id_enfermedad', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ExpedienteCO.Enfermedad')),
            ],
            options={
                'db_table': 'padre_padece_enfermedad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RealizacionconsultaJoinCita',
            fields=[
                ('id_cita', models.ForeignKey(db_column='id_cita', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ExpedienteCO.Cita')),
            ],
            options={
                'db_table': 'realizacionconsulta_join_cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolAccedeAMenu',
            fields=[
                ('id_menu', models.ForeignKey(db_column='id_menu', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ExpedienteCO.Menu')),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('add', models.NullBooleanField()),
                ('edit', models.NullBooleanField()),
                ('list', models.NullBooleanField()),
                ('del_field', models.NullBooleanField(db_column='del')),
            ],
            options={
                'db_table': 'rol_accede_a_menu',
                'managed': False,
            },
        ),
    ]
